#!/bin/bash

rl=0

if ! type perl > /dev/null 2>& 1; then
  if uname | grep -i 'darwin' > /dev/null; then
    echo 'Requires perl to start on OSX.' >& 2
    exit 1
  fi
  rl=1
fi

if test $rl -eq 1; then
  file=$(readlink -f "$0")
else
  file=$(perl -MCwd -e "print Cwd::realpath('$0')")
fi

dir=$(dirname "$file")

shopt -s nullglob

for file in ${dir}/{bench,bin,lib,test,test/util}/*.js; do
  cat "$file" \
    | sed 's/0b\([0-1]\+\)n/0b\1/g' \
    | sed 's/0o\([0-7]\+\)n/0o\1/g' \
    | sed 's/0x\([0-9a-fA-F]\+\)n/0x\1/g' \
    | sed 's/\([0-9]\+\)n/\1/g' \
    | sed "s/'bigint'/'number'/g" \
    | sed "s/BigInt(/Number(/g" \
    | eslint --stdin --stdin-filename "$file"
done

shopt -u nullglob
